version: '2.4'

services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: always

  frontier:
    image: crawlercommons/url-frontier
    container_name: frontier
    command: rocksdb.path=/crawldir/rocksdb
    ports:
      - "127.0.0.1:7071:7071"
    volumes:
      - ./data/stormcrawler-docker:/crawldir

  builder:
    image: schubec/storm_maven:2.4.0-temurin
    container_name: builder
    depends_on:
      - nimbus
    volumes:
      - ./data/crawldata:/crawldata

  nimbus:
    image: storm:2.4.0-temurin
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - ./data/storm-nimbus-logs:/logs

  supervisor:
    image: storm:2.4.0-temurin
    container_name: supervisor
    command: storm supervisor -c worker.childopts=-Xmx%HEAP-MEM%m
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ./data/storm-supervisor-logs:/logs

  ui:
    image: storm:2.4.0-temurin
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data/storm-ui-logs:/logs

  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx3750m"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"
    mem_limit: 4096m
    ports:
      - 9200:9200
     
  kibana:
    image: kibana:7.16.3
    container_name: kibana
    restart: always
    environment:
      OPENSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"
    mem_limit: 1024m
    ports:
      - 5601:5601
